### ISSUE TITLE
Error during installation Javapath

### ISSUE THREAD

**Issue by biglimp** [j3r3m1/urock_processing#27]
Some issue related to java path.

![image](https://user-images.githubusercontent.com/11908356/202205795-3663a49e-df69-4352-b0b3-6c46840fb904.png)

**Comment by j3r3m1** [comment]
can you give me what you get when you type "java -version" in a terminal ?

**Comment by KarzoKalori** [comment]
![JavaUROCK](https://user-images.githubusercontent.com/83512843/202217380-b9506e06-5f5e-411a-b747-7978693dde7f.jpg)

**Comment by KarzoKalori** [comment]
I have windows 11 installed on my computer

**Comment by j3r3m1** [comment]
I should add an error message that URock cannot find any Java installation on the computer
