### ISSUE TITLE
Error during processor run

### ISSUE THREAD

**Issue by KarzoKalori** [j3r3m1/urock_processing#29]
Java Exception

[Urock_Log.txt](https://github.com/j3r3m1/urock_processing/files/10022743/Urock_Log.txt)
![urockfel](https://user-images.githubusercontent.com/83512843/202210057-528383de-2a47-4dc9-8628-15f2b78e426a.jpg)

**Comment by j3r3m1** [comment]
Can you share your building table ?

**Comment by KarzoKalori** [comment]
Of course, here you have it.

[building_data.zip](https://github.com/j3r3m1/urock_processing/files/10023039/building_data.zip)

**Comment by j3r3m1** [comment]
Should be solved if you use the new version. Feel free to reopen it if not
