### ISSUE TITLE
issues for models with a different wind angle of incidence

### ISSUE THREAD

**Issue by simonmarti1992** [j3r3m1/urock_processing#33]
Dear urock users,
I'm facing a problem when I perform a simulation by varying the angle of incidence of the wind. 
- for DIR = 0°, no problem
- for DIR = 22°, I get the following error message:
```
DatabaseError: org.h2.jdbc.JdbcSQLDataException: Division by zero: "CAST(7.96999999973923 AS DOUBLE)"
Division by zero: "CAST(7.96999999973923 AS DOUBLE)"; SQL statement:
CREATE INDEX IF NOT EXISTS id_DOWNWIND_FACADE_ID_ZONE_LIMITS_CAVITY_20230116135846 ON ZONE_LIMITS_CAVITY_20230116135846(DOWNWIND_FACADE_ID); [22012-200]
    
```

You will find attached the model used
[buildings_3857_notnan.zip](https://github.com/j3r3m1/urock_processing/files/10426036/buildings_3857_notnan.zip)
Have a nice day

**Comment by j3r3m1** [comment]
Thanks for reporting. I will check that asap.

**Comment by j3r3m1** [comment]
I can not reproduce the error, everything works fine for me.

Can you give more informations about both the error (if you have more log) and the parameters used for your calculations (mesh size, dz for now) ?

**Comment by j3r3m1** [comment]
It seems the error comes when the wind is 22.5 degree rather than 90 degrees if I understand well ?

**Comment by j3r3m1** [comment]
Should be solved with new commit : https://github.com/j3r3m1/urock_processing/commit/8b3955d1db7bf20d4a79f0061470b92f52342b3e

**Comment by simonmarti1992** [comment]
It seems fixed now 👍 
well done
