### ISSUE TITLE
No result when using a raster

### ISSUE THREAD

**Issue by KarzoKalori** [j3r3m1/urock_processing#34]
URock without raster data takes about 15 minutes to perform over the area attached. With raster data, I can't manage to get a result even after two whole days of run. 

[UR-G.zip](https://github.com/j3r3m1/urock_processing/files/10709118/UR-G.zip)
![URock Input](https://user-images.githubusercontent.com/83512843/218136576-4265db6e-d8ed-4710-bf9e-d5757b9b51a9.PNG)

**Comment by j3r3m1** [comment]
Sorry for not responding. There is indeed a strange behavior. Can you tell me at what stage the algorithm is working forever (you can add a screenshot if you are not sure) ?

As a temporal solve, you might use the processing within a Python script (cf. https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/PythonProcessing2.html).

**Comment by j3r3m1** [comment]
Additionally, can you have a try using 3 m for horizontal resolution instead of 2 ? Because it works fine for me with 3 m.
![image](https://user-images.githubusercontent.com/13120405/224372115-3695e939-041f-406a-ab96-d10670fda9c0.png)

**Comment by KarzoKalori** [comment]
This is how it looks as it is original, with 3 m horizontal resolution, with 3 m horizontal and 3 m vertical resolution. I ran all three options for 2 hours without any result. 

![UR1](https://user-images.githubusercontent.com/83512843/224442227-08f10359-8be3-402d-88fa-d2a0ce93dbc0.png)
![UR2](https://user-images.githubusercontent.com/83512843/224442247-69e31c7e-09df-4169-88d1-06d02e56c7b7.png)

**Comment by j3r3m1** [comment]
Well the behavior seems quite unpredictable but I have retried today and got the same problem. It seems the 1 m resolution is taken somewhere, thus exploding the size of the objects used (the database reached 10 Go on my computer before I stopped it). I will investigate this point when I will find time.

**Comment by KarzoKalori** [comment]
I just tested the new version and it works really well! Good work @j3r3m1 !

**Comment by j3r3m1** [comment]
thanks for reporting !
